import { ProfileTab } from "@/components/dashboardTabs/ProfileTab.jsx";
import { SupportTab } from "@/components/dashboardTabs/supportTab.jsx";
import { PortfolioTab } from "@/components/dashboardTabs/PortfolioTab.jsx";
import { ReferralTab } from "@/components/dashboardTabs/ReferralTab.jsx";
import { WithdrawalsTab } from "@/components/dashboardTabs/WithdrawalTab.jsx";
import { BuySharesModal } from "@/components/dashboardTabs/BuySharesModal.jsx";
import { BuySharesTab } from "@/components/dashboardTabs/BuySharesTab.jsx";
import { DashboardTab } from "@/components/dashboardTabs/DashboardTab.jsx";
import { WalletTab } from "@/components/dashboardTabs/WalletTab.jsx";
import { DividendsTab } from "@/components/dashboardTabs/DividendTab.jsx";

export { DashboardTab };
export { BuySharesTab };
export { BuySharesModal };
export { WalletTab };
export { WithdrawalsTab };
export { ReferralTab };
export { PortfolioTab };
export { SupportTab };
export { ProfileTab };
export { DividendsTab };
